kind: Secret
apiVersion: v1
metadata:
  name: sdm-relay-secret
type: Opaque
data:
  token: N/A
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sdm-relay-deployment
  labels:
    app: sdm-relay
spec:
  replicas: 1 # must always be 1.
  selector:
    matchLabels:
      app: sdm-relay
  template:
    metadata:
      labels:
        app: sdm-relay
    spec:
# You may use node affinity to ensure that these containers are only
# deployed to publicly visible nodes.
# This doesn't work with fargate profiles
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: alpha.eksctl.io/nodegroup-name
#                operator: In
#                values:
#                - ng-1
      containers:
      - name: sdm-relay
        image: quay.io/sdmrepo/relay:latest
        imagePullPolicy: Always
        env:
        - name: SDM_ORCHESTRATOR_PROBES
          value: ":9090"
        - name: SDM_RELAY_TOKEN
          valueFrom:
            secretKeyRef:
              name: sdm-relay-secret
              key: token
        livenessProbe:
          httpGet:
            path: /liveness
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: sdm-relay-service
  labels:
    app: sdm-relay
spec:
  type: "NodePort"
  selector:
    app: sdm-relay
  ports:
  - name: gateway
# or relay
    port: 30001
    targetPort: 5000
    nodePort: 30001
# You may use externalIPs as a way to get a stable IP configuration.
# then map 80.11.12.10 to sdmrelay.mycompany.com
  externalIPs:
  - 34.220.97.45
